safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Zhaoyun's Blog
host: hezhaoyun.github.io
desc: 往美得想，往好得做！

custom:
    category:
        tech: 技术
        design: 设计
        story: 故事
        pm: 产品
    categories:
      - name:  pm
        title: 产品
      - name:  design
        title: 设计
      - name:  tech
        title: 技术
      - name:  story
        title: 故事

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 贺照云
        email: hezhaoyun@outlook.com
        disqus: zhaoyun                             # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: hezhaoyun                           # GitHub账号
        gravatar: 889c164a955cbfb495ab575626f85e56  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
